[package]
name = "birl"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = { version = "0.4.26" , features = ["kv"] }
serde = { version = "1.0.218", features = ["derive", "serde_derive"] }
xitca-web = { version = "0.6.2", features = ["json", "logger"] }
